#!/bin/bash

notice(){
    RED="\033[0;31m"
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'`请在这里插入代码片段`
    # ... ADD MORE COLORS
    NC='\033[0m' # No Color

    printf "${!1}${2} ${NC}\n"
}

showFailMsg(){
	notice "RED"  "The prefix can only be feat、docs、fix、style、refactor、perf、test、chore."
	showPrefixNotice
	showCommitExample
}

showPrefixNotice(){
	echo "Allowed prefix:"
	echo "  feat 开发新需求"
	echo "  fix 修复bug"
	echo "  docs 修改文档"
	echo "  style 调整代码格式"
	echo "  refactor 代码重构"
    echo "  perf 性能优化"
	echo "  test 增加单元测试号相关"
	echo "  chore 修改配置相关"
}

showCommitExample(){
	notice "GREEN"  "Usage example:"
	echo "	feat(sda): Add sda list feat= "
	echo "	fix(connect): Fix base request timeout error fix="
	echo "	docs: Add schema useage demo"
}

commit_msg=$(cat "${1:?Missing commit message file}")
valid=0
if [[ $commit_msg =~ ^(((feat)|(fix)|(docs)|(style)|(refactor)|(perf)|(test)|(chore))(\(.*\))?:){1} ]]; then
	if [[ $commit_msg =~ ^(((feat)|(fix))(\(.*\))?:){1} ]]; then
		if [[ $commit_msg =~ ((feat=[0-9]+)|(fix=[0-9]+))+ ]]; then
			exit 0
		else
			notice "RED"   "请带上feat Id或者bug Id相关信息"
			showPrefixNotice
			showCommitExample
			exit 1
		fi
	else
		exit 0
	fi
else
	showFailMsg
	exit 1
fi